# Generated by Django 2.0.3 on 2018-03-23 12:06

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.dynamic_profile_img_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='script',
            field=models.TextField(blank=True, max_length=50000),
        ),
    ]
