# Generated by Django 2.0.3 on 2018-03-23 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180323_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-recorded_date']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='youtube_link',
            new_name='youtube_id',
        ),
    ]
